### ISSUE TITLE
Clicking the top menu directory link should always load the "Featured suppliers" landing page

### ISSUE THREAD

**Issue by macep** [macep/MakeriesDirectory#37]
It doesn't always seem to load the featured suppliers page.
To recreate:
Click on the top menu directory link (correct page displays the first time you click this link or if you click on it and do a browser reload)
Click on the LHM Search Suppliers (to go to the All suppliers page)
Click on the top menu Directory link again: nothing happens; do a browser reload, and then the correct Featured Suppliers shows

**Comment by Cristialt** [comment]
The way it worked is the way I understood we need it; updated now
