### ISSUE TITLE
The "Verify your Email" Link from the email confirm takes you to the user registration page

### ISSUE THREAD

**Issue by macep** [macep/MakeriesDirectory#43]
It's a bit confusing as the user has just come from filling out the registration form. If this link can't direct you to the page you originally clicked then it should load a verification success page then redirect to the directory landing page

**Comment by Cristialt** [comment]
ok, but the user is not autocompleted and the password field not focused yet since the mailchimp is now blck I I need that piece ot flow to get the necessary information from the cookies

**Comment by Cristialt** [comment]
user is taken to the login screen and will be prefilled with their email when the validation succeded
