### ISSUE TITLE
The error messages disappear too quickly if the user account already exists

### ISSUE THREAD

**Issue by macep** [macep/MakeriesDirectory#44]
And they seem to only display once. i.e. if I miss the message and try and click register again it seems like nothing happens and there's nothing to tell me what's wrong.

Can we leave error messages on the screen so user can see what they need to change - I think we should do this for all messages.

Please also remove the error number from the message. i.e. No need to display the "400"

**Comment by Cristialt** [comment]
I made so that now the notifications are managed and centralized and displayed dynamically; also they remain on the user interface until they continue editting or close it
