### ISSUE TITLE
I still don't understand why we need to have a short username and an email?

### ISSUE THREAD

**Issue by macep** [macep/MakeriesDirectory#46]
Why can't we just use the email address as the username, so user's don't have to remember two pieces of information? Most sites just use email address as username.

**Comment by Cristialt** [comment]
it's mandatory in auth0js api

**Comment by macep** [comment]
I should rephrase: 
Can we use the email address as the username? So the user only has to remember one thing...

**Comment by Cristialt** [comment]
so I can't just copy the email they filled in under the hood and assign it to the username property; would be simple

**Comment by Cristialt** [comment]
but the form is not complicated at all, even a tree could read and fill it
