### ISSUE TITLE
new registration not appearing in Mailchimp

### ISSUE THREAD

**Issue by macep** [macep/MakeriesDirectory#49]
I just tried registering a new user (macep002@mailinator.com/ username:macep002) and it didn't appear in mailchimp

I also tried logging in as a new user using Google (amber.mace@gmail.com) and that hasn't appeared either.

Also can you remind me where to login into OAuth again so I can check the user was set up correctly there (and add to docs please)

Thanks

**Comment by Cristialt** [comment]
here are the registered users -> https://manage.auth0.com/#/users
here is hte mallchimp list -> https://us17.admin.mailchimp.com/lists/members/?id=42159

social media based account are not added to th emailchimp list - I added a tasks (#50) for that

**Comment by macep** [comment]
macep002@mailinator.com didn't get registered in mailchimp although it successfully completed the oauth process

**Comment by macep** [comment]
I'm not sure where to look to see what happened in Mailchimp. Are there any API logs, or can you tell me where the logs are on the client app? At least we can see whether it tried to pass the data to MailChimp or not?

**Comment by macep** [comment]
Just tested again with a new user macep003@mailinator.com and it's not appearing in MailChimp still. See my comments above, I'm not sure how to further investigate... 
When is the mailchimp account created? When the user clicks the verify link or the first time they sign in on the website?

**Comment by Cristialt** [comment]
it works now, 
when the user clicks the verification link in the email, they're sent in the browser in that PHP file which reads a cookie to grab some infor for the mailchimp account, the mailchimp list is updated and then the user sent to the app inthe login page with a new cookie that we use for further processing in the background; I tested few times and all is well

**Comment by macep** [comment]
Sounds good! I’ll test it later today. 

So we could call the php file for mailchimp whenever we need to.

Peter Mace
peter.mace@gmail.com
07971 686 363
